nelmio_cors:
  paths:
    '^/':
      allow_origin: [ '*' ]
      allow_headers: [ 'X-AUTH-TOKEN', 'Origin', 'X-Requested-With', 'Content-Type', 'Accept' ]
      allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
      max_age: 3600